### ISSUE TITLE
服务端运行报错，报MongoError

### ISSUE THREAD

**Issue by liesauer** [JakeLaoyu/qiniu-files-manager#22]
这小玩意不会还要MongoDB吧？
```
E:\Projects\qiniu-files-manager\server\node_modules\connect-mongo\node_modules\mongodb\lib\mongo_client.js:421
          throw err
          ^
Error [MongoError]: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoError'
}]
    at Pool.<anonymous> (E:\Projects\qiniu-files-manager\server\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at Pool.emit (events.js:315:20)
    at Connection.<anonymous> (E:\Projects\qiniu-files-manager\server\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:422:26)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (E:\Projects\qiniu-files-manager\server\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by JakeLaoyu** [comment]
mongodb 做的 session 持久化
